% Complexity Analysis Visualization

figure;
hold on;
n = 1:100;

y0 = ones(size(n));
plot(n, y0, 'DisplayName', 'WriteCallback - O(1)');
y1 = ones(size(n));
plot(n, y1, 'DisplayName', 'if - O(1)');
y2 = ones(size(n));
plot(n, y2, 'DisplayName', 'main - O(1)');
y3 = ones(size(n));
plot(n, y3, 'DisplayName', 'detenerFlask - O(1)');
y4 = ones(size(n));
plot(n, y4, 'DisplayName', 'iniciarFlask - O(1)');
y5 = ones(size(n));
plot(n, y5, 'DisplayName', 'stopFlask - O(1)');
plot(n, y6, 'DisplayName', 'iniciarFlaskThread - O(n^1)');
plot(n, y7, 'DisplayName', 'stopFlaskThread - O(n^1)');
y8 = ones(size(n));
plot(n, y8, 'DisplayName', 'iniciarFlaskVizSalida - O(1)');
y9 = ones(size(n));
plot(n, y9, 'DisplayName', 'iniciarFlaskGrafico - O(1)');
y10 = ones(size(n));
plot(n, y10, 'DisplayName', 'iniciarFlaskVisEntrada - O(1)');
y11 = ones(size(n));
plot(n, y11, 'DisplayName', 'iniciarFlaskVis - O(1)');
plot(n, y12, 'DisplayName', 'mostrarGrafico - O(n^1)');
y13 = ones(size(n));
plot(n, y13, 'DisplayName', 'MenuBusquedaBinaria - O(1)');
plot(n, y14, 'DisplayName', 'partition - O(n^1)');
y15 = ones(size(n));
plot(n, y15, 'DisplayName', 'quickSort - O(1)');
plot(n, y16, 'DisplayName', 'bubbleSortPass - O(n^1)');
y17 = ones(size(n));
plot(n, y17, 'DisplayName', 'bubbleSortRecursive - O(1)');
y18 = ones(size(n));
plot(n, y18, 'DisplayName', 'bubbleSort - O(1)');
plot(n, y19, 'DisplayName', 'ordenarLista - O(n^1)');
plot(n, y20, 'DisplayName', 'ordenarListaBubbleSort - O(n^1)');
plot(n, y21, 'DisplayName', 'ordenarListaShellSort - O(n^3)');
plot(n, y22, 'DisplayName', 'radixSortByString - O(n^3)');
plot(n, y23, 'DisplayName', 'radixSortByInt - O(n^3)');
plot(n, y24, 'DisplayName', 'ordenarListaPorRadix - O(n^1)');

title('Complexity Analysis');
xlabel('Input Size (n)');
ylabel('Operations');
legend('show');
grid on;
hold off;
